name: fb-clone

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app

        depends_on:
            - users
            - postwrite
            - friendship

        networks:
            - public-network
            - private-network

    users:
        build:
            context: ./users
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./users/.env
        ports:
            - 8010:8000
        volumes:
            - ./users:/app
        depends_on:
            - users-db
            - rabbitmq
        networks:
            - private-network

    users-db:
        image: postgres:17
        restart: always
        env_file:
            - ./users/.env
        volumes:
            - users-db:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - private-network

    postwrite:
        build:
            context: ./postwrite
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./postwrite/.env
        ports:
            - 8020:8000
        volumes:
            - ./postwrite:/app
            - ./backups:/backups
        depends_on:
            - posts-write-db
            - rabbitmq
            - redis
        networks:
            - private-network

    posts-write-db:
        image: postgres:17
        restart: always
        env_file:
            - ./postwrite/.env
        volumes:
            - posts-write-db:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - private-network
        ports:
            - 5432:5432

    friendship:
        build:
            context: ./friendship
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./friendship/.env
        ports:
            - 8030:8000
        volumes:
            - ./friendship:/app
        depends_on:
            - friendship-db
            - rabbitmq
            - redis
        networks:
            - private-network

    friendship-db:
        image: neo4j:5.23.0-community-bullseye
        restart: always
        env_file:
            - ./friendship/.env
        volumes:
            - friendship-db:/data
            - ./backups:/backups
        networks:
            - private-network
        ports:
            - 7474:7474
            - 7687:7687

    rabbitmq:
        restart: always
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        env_file:
            - ./.env
        networks:
            - private-network

    chat:
        build:
            context: ./chat
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./chat/.env
        ports:
            - 8040:8000
        volumes:
            - ./chat:/app
            - ./backups:/backups
        depends_on:
            - chat-db
            - rabbitmq
            - redis-chat
        networks:
            - public-network
            - private-network

    chat-db:
        image: postgres:17
        restart: always
        env_file:
            - ./chat/.env
        volumes:
            - chat-db:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - private-network

    redis:
        restart: always
        image: redis:7.4.1-alpine
        ports:
            - 6379:6379
        networks:
            - private-network

    redis-chat:
        restart: always
        image: redis:7.4.1-alpine
        networks:
            - private-network

    gateway:
        image: nginx:stable
        restart: always
        ports:
            - 888:80
        volumes:
            - ./api/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - public-network
            - private-network

volumes:
    users-db:
    posts-write-db:
    friendship-db:
    chat-db:

networks:
    private-network:
    public-network:
