name: fb-clone

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app

        depends_on:
            - users
            - postwrite
            - friendship

        networks:
            - public-network

    users:
        hostname: users
        build:
            context: ./users
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./users/.env
        volumes:
            - ./users:/app
        depends_on:
            - users-db
            - rabbitmq
        networks:
            - private-network

    users-db:
        hostname: users-db
        image: postgres:17
        restart: always
        env_file:
            - ./users/.env
        volumes:
            - users-db:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - private-network

    postwrite:
        hostname: posts
        build:
            context: ./posts
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./posts/.env
        volumes:
            - ./posts:/app
            - ./backups:/backups
        depends_on:
            - posts-write-db
            - rabbitmq
            - redis
        networks:
            - private-network

    posts-write-db:
        hostname: posts-db
        image: postgres:17
        restart: always
        env_file:
            - ./posts/.env
        volumes:
            - posts-write-db:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - private-network

    friendship:
        hostname: friends
        build:
            context: ./friends
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./friends/.env
        volumes:
            - ./friends:/app
        depends_on:
            - friendship-db
            - rabbitmq
            - redis
        networks:
            - private-network

    friendship-db:
        hostname: friends-db
        image: neo4j:5.23.0-community-bullseye
        restart: always
        env_file:
            - ./friends/.env
        volumes:
            - friendship-db:/data
            - ./backups:/backups
        networks:
            - private-network

    rabbitmq:
        hostname: rabbitmq
        restart: always
        image: rabbitmq:3-management
        env_file:
            - ./.env
        networks:
            - private-network

    chat:
        hostname: chat
        build:
            context: ./chat
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./chat/.env
        volumes:
            - ./chat:/app
            - ./backups:/backups
        depends_on:
            - chat-db
            - rabbitmq
            - redis-chat
        networks:
            - private-network

    chat-db:
        hostname: chat-db
        image: postgres:17
        restart: always
        env_file:
            - ./chat/.env
        volumes:
            - chat-db:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - private-network

    redis:
        hostname: redis
        restart: always
        image: redis:7.4.1-alpine
        networks:
            - private-network

    redis-chat:
        hostname: redis-chat
        restart: always
        image: redis:7.4.1-alpine
        networks:
            - private-network

    gateway:
        hostname: apigateway
        image: nginx:stable
        restart: always
        ports:
            - 888:80
        volumes:
            - ./api/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - public-network
            - private-network

volumes:
    users-db:
    posts-write-db:
    friendship-db:
    chat-db:

networks:
    private-network:
    public-network:
